### PR TITLE
Add cargo clippy and fmt to workflow config.

### LINKED ISSUE #57: Apply clippy and setup github actions

### PR DESCRIPTION
**Pull request by ssr-yuki**
closes #57

### CODE REVIEW

**Comment by ssr-yuki** [comment]
@OTL How should we treat with this?
https://github.com/openrr/k/runs/2784199886?check_suite_focus=true#step:4:313

**Comment by OTL** [comment]
Please say @taiki-e , help me!

**Comment by taiki-e** [comment]
Some of style and complexity lints are almost like pedantic lint, so let's ignore them.

**Review by OTL — APPROVED** [review]
Thanks!!

**Pull request merged**
